# server config
server:
  port: 8088
  undertow:
    accesslog:
      dir: ../logs/
      enabled: true
      pattern: oss
      prefix: access_log
      suffix: .log
      rotate: true
  compression:
    enabled: true
    mime-types: text/html,text/html,text/css,text/javascript,application/json,application/xml,text/plain


spring:
  profiles:
    active: default
  application:
    name: lb-taobao-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bank?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Qwer1234
    hikari:
      connection-init-sql: SET NAMES utf8mb4
      maximum-pool-size: 100
      minimum-idle: 5
      connection-test-query: select 1
      idle-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  redis:
    database: 0
    host: localhost
    port: 6379
    ##password: 123456
    timeout: 3000s
  main:
    bannerMode: "off"

logging:
  config: classpath:logback.xml

# swagger config
swagger:
  enable: true
